check vdisk existence

diff --git a/ibm_mkvdiskhostmap b/ibm_mkvdiskhostmap
--- a/ibm_mkvdiskhostmap
+++ b/ibm_mkvdiskhostmap
@@ -18,18 +18,26 @@ if [ -z "${_dev}" -o -z "${_hosts}" -o -z "${_vdisk}" ]; then
     exit 2
 fi
 
-typeset _f1 _f2 _id _f4
+typeset _f1 _f2 _id _f4 _vname _f6
 typeset _maxid=0
+typeset _vdiskok=0
 
 # Check SCSI ID in use, and get the next available
-while read _f1 _f2 _id _f4; do
+# Check vDisk existence
+while read _f1 _f2 _id _f4 _vname _f6; do
     [ "${_f1}" = "id" ] && continue
     if [ "${_id}" = "${_scsiid}" ]; then
         echo "ERROR: SCSI ID already in use: ${_scsiid}"
         exit 1
     fi
+    [ "${_vname}" = "${_vdisk}" ] && _vdiskok=1
     [ "${_id}" -ge "${_maxid}" ] && _maxid=$((_maxid + 1))
 done < <(ssh -n "${_dev}" lshostvdiskmap)
+
+if [ "${_vdiskok}" != "1" ]; then
+    echo "ERROR: inexistent vDisk '${_vdisk}'"
+    exit 1
+fi
 
 typeset _scsi
 if [ -z "${_scsiid}" ]; then
